# Generated by Django 4.0.3 on 2022-03-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='creaed',
            new_name='created',
        ),
    ]
